name: Check Runners

on:
  push:
    branches:
      - vr/check-runners
  workflow_dispatch:

jobs:
  build-xenial:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: lscpu
        run: lscpu
